[package]
name = "wasmi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
clap = "3.0.0-beta.2"
env_logger = "0.8.3"
log = "0.4.14"
