name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [nightly, beta, stable]

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: build
        uses: actions-rs/cargo@master
        with:
          command: build

      - name: test
        uses: actions-rs/cargo@master
        with:
          command: test

      - name: fuzzing
        run: |
          cargo install cargo-fuzz
          cargo fuzz run decode --jobs 4 -- -runs=10000

  check_fmt_and_docs:
    name: Checking fmt and docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions-rs/toolchain@master
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt

      - name: setup
        run: |
          rustup component add rustfmt
          rustc --version

      - name: fmt
        run: cargo fmt --all -- --check
